version: "3.1"
services:
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=gGyz5vOxBMaTlAmbRE2GDZiCuSk=
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
